rebase mainline (#11)
* mklove: make zlib test program compilable

The test program that is used at compile-time to detect whether zlib is
available fails to compile due to `NULL` being undefined:

```
_mkltmpyos55w.c:5:20: error: use of undeclared identifier 'NULL'
     z_stream *p = NULL;
                   ^
1 error generated.
```

This means that zlib availability is only automatically detected when
using pkg-config.

Import `stddef.h` (which defines `NULL`) in the test program, allowing
zlib to be automatically detected via a compilation check.

* Travis: New secure env vars

* AppVeyor: rotate access keys

* Travis: show sha256sums of artifacts prior to deploy

* Add MSVC 140 runtimes (for packaging)

* Add 'ssl.ca.pem' property (#2380)

* Improve nuget release script

 - Verify artifact file contents and architectures.
 - Verify that artifact attributes match.
 - Get README, CONFIG,.. etc, from artifacts instead of local source tree
   (which may not match the released version).

* Bump to version 1.8.2

(Skipping 1.8.1 due to dotnet release with that number)

* mklove: fix static bundle .a generation on osx

* mklove: portable checksum checking for downloads

* mklove: allow --source-deps-only OpenSSL builds on OSX

* Don't build ancient OSX Sierra artifacts

* Travis: reduce build minutes (tagged jobs)

* Travis: use --source-deps-only for dependencies instead of using homebrew

Homebrew is fantastically slow to update to Travis-CI, and it is burning
build credits like crazy.

* mklove: added mklove_patch

* mklove: show more of failed build logs

* mklove openssl installer: workaround build issue in 1.1.1l on osx.

* Apply OpenSSL PR 16409 patch to fix 1.1.1l build issues on OSX

* Travis: Remove -Werror from OSX worker since OpenSSL builds have quite a few warnings

* mklove: try both wget and curl for archive downloads

* Don't overwrite ssl.ca.location on OSX (#3566)

* Travis: bump Linux base builder from trusty to xenial to circumvent ISRG cert expiry

.. which causes older versions of OpenSSL+curl to fail to download OpenSSL..

* AddOffsetsToTxn Refresh errors did not trigger coord refresh (#3571)

* Ensure timers are started even if timeout is 0

* Transactional producer: Fix possible message loss on OUT_OF_ORDER_SEQ error (#3575)

* Mock push_request_errors() appended the errors in reverse order

* Update list of supported KIPs

* Add rd_buf_new()

* Import cJSON v1.7.14

URL: https://github.com/DaveGamble/cJSON
Tag: v1.7.14
SHA: d2735278ed1c2e4556f53a7a782063b31331dbf7

* Added HTTP(S) client using cURL

* Add HTTP(S) client using cURL

* Fix uninitialized warning on msvc

* Remove commented-out printfs

* Remove stray license include in librdkafka vcxproj

* librdkafka.vcxproj: remove stale OpenSSL paths and enable Vcpkg manifests

* mklove: but all built deps in the same destdir and set up compiler flags accordingly

This fixes some issues when dependency B depends on dependency A, in this
case for libcurl that depends on OpenSSL, to make it find the OpenSSL
libraries, pkg-config files, etc.

* mklove: don't include STATIC_LIB_..s in BUILT_WITH

* mklove: Some autoconf versions seem to need a full path to $INSTALL

* curl: disable everything but HTTP(S)

* Added string splitter and kv splitter

* OAuth/OIDC: Add fields to client configuration (#3510)

* Implement native Win32 IO/Queue scheduler (WSAWaitForMultipleEvents)

This removes the internal loopback connections (one per known broker)
that were previously used to trigger io-based queue wakeups.

* Add vcpkg_installed to gitignore

* Left-trim spaces from string configuration values

This makes it easier to use Bash on Windows where a prefixing / is translated
into the MinGW32 file system root.

* Mark rd_kafka_conf_kv_split as unused .. until it's used.

* rd_kafka_queue_get_background() now creates the background thread

* Added custom SASL callback queue

* Fix test flags for 0122 and 0126

* Test 0119: remove unused code

* Direct questions to the github discussions forum to keep issue load down

* Add clang-format style checking and fixing

* Add Python style checking and fixing

* Run style-checker with Github Actions

* Automatic style fixes using 'make style-fix'

* Manual style fixes of Python code

* Avoid use of FILE* BIOs to circumvent OpenSSL_Applink requirement on Windows (#3554)

* sasl: Enable AWS_MSK_IAM SASL mechanism (#3402)

AWS_MSK_IAM is a new SASL mechanism for
authenticating clients to AWS MSK Kafka
clusters and use IAM-based controls to
set Kafka ACLs and permissions. This change
provides support to allow clients to pass
AWS credentials at runtime which is used
to build the SASL payload and authenticate
clients to IAM enabled MSK clusters. It adds
a new SASL mechanism, AWS_MSK_IAM, as well
as configuration options to set the following:
* AWS access key id
* AWS secret access key
* AWS region
* AWS security token
The SASL handshake requires a specific payload
that is described here:
https://github.com/aws/aws-msk-iam-auth

* Add curl to doozer build

* Address comments (#5)

* sasl: Enable STS credential refresh (#7)

* Add 'ssl.ca.pem' property (#2380)

* Updated PROPS_IDX_MAX

* Remove HEAD

* Fix compile errors

* Fix consumer

Co-authored-by: Chris Novakovic <chris@chrisn.me.uk>
Co-authored-by: Magnus Edenhill <magnus@edenhill.se>
Co-authored-by: Jing Liu <jl5311@nyu.edu>